"""
whatsapp.py

WhatsApp communication adapter.

This file is responsible for:
1. Receiving a WhatsApp message in our internal format.
2. Passing it to the existing conversation workflow.
3. Returning the response that should be sent back to WhatsApp.

The booking logic itself remains inside Conversation.
"""

from backend.session_manager import SessionManager


class WhatsAppAgent:

    def __init__(self):
        """
        Create a session manager for WhatsApp conversations.
        """

        self.session_manager = SessionManager()

    def process_message(self, sender_id, message):
        """
        Process one WhatsApp message.

        sender_id:
            Unique identifier for the WhatsApp customer.

        message:
            Text sent by the customer.
        """

        # Get the conversation belonging to this customer.
        conversation = self.session_manager.get_conversation(
            sender_id
        )

        # Send the message into our existing booking workflow.
        result = conversation.process_message(
            message
        )

        # Return the response generated by the booking workflow.
        return {
            "response": result["response"],
            "booking": result["booking"]
        }